### PR TITLE
Add super basic specs

### LINKED ISSUE #26: Implement specs
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

### PR DESCRIPTION
**Pull request by Arcanemagus**
Tests just the minimum to ensure it's still working.

Fixes #26.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@dhagerty9009 Feel free to either merge this and do the rest in further commits, or just work on this branch as it's on the main repo :wink:.

**Comment by dhagerty9009** [comment]
Thanks dude. I’ll just work on this branch and get things done tomorrow!

--
David Hagerty
404-245-6810
Email  |  Twitter  | GitHub | Blog

"To be nobody but yourself in a world which is doing its best, night and day, to make you everybody else means to fight the hardest battle which any human being can fight; and never stop fighting." - E. E. Cummings

On February 3, 2016 at 7:58:44 PM, Landon Abney (notifications@github.com) wrote:

@dhagerty9009 Feel free to either merge this and do the rest in further commits, or just work on this branch as it's on the main repo .

**Comment by troessner** [comment]
Nice one! 
Additional suggestion: I think it would be great to have at least one spec that ensures that the `Reek` configuration file is honored, e.g. via using something like:

```Yaml
----
IrresponsibleModule:
  enabled: false
```

and then apply that to spec/fixtures/bad_but_masked.rb :

```
class Dirty
end
```

**Comment by Arcanemagus** [comment]
@troessner You can help @dhagerty9009 out and PR to this branch if you want :wink:.

**Comment by troessner** [comment]
Unfortunately my javascript-fu is limited to "i have used jquery 7 ago" :laughing:

**Pull request merged**
